version: latest

services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code/INNOWISE
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php
    image: php:fpm
    command:
      - /bin/sh
      - -c
      - |
        docker-php-ext-install mysqli
        echo "extension installed.....starting php-fpm"
        php-fpm
    volumes:
        - ./:/code/INNOWISE
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 28041972IraBel!
      MYSQL_DATABASE: innowise
      MYSQL_PASSWORD: 28041972IraBel!
    ports:
      - "9906:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
