version: latest

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/code/INNOWISE
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:fpm
    command:
      - /bin/sh
      - -c
      - |
        docker-php-ext-install mysqli 
        echo "extension installed.....starting php-fpm........................................"
        php-fpm
    volumes:
        - ./:/code/INNOWISE

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
